import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {ErrorMessage, Field, Form, Formik} from "formik";
import axios from "axios";

export default function Home() {

  return (
      <div className={styles.container}>
        <Head>
          <title>Abogado Pro</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon"/>
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Abogado <a href="https://nextjs.org">Pro</a>
          </h1>

          <p className={styles.description}>
            Formulario de contacto, ingrese sus datos y nos contactaremos con usted.
          </p>

          <div className={styles.grid}>
            <div
                className={styles.card}
            >
              <h2>Describa su situación actual</h2>
              <div>
                <Formik
                    initialValues={{email: '', content: '', type: ''}}
                    onSubmit={(values, {setSubmitting, resetForm}) => {
                      axios.post('/api/mail/sendMail', values)
                      .then(function (response) {
                        alert(response.data.msg);
                      })
                      .catch(function (error) {
                        alert("Hubo un error al contactar, intente más tarde.");
                      });
                      resetForm();
                    }}
                >
                  {({isSubmitting}) => (
                      <Form>
                        <div className="form-group">
                          <label>Correo</label>
                          <Field type="email" name="email" className="form-control"/>
                          <ErrorMessage name="email" component="div"/>
                        </div>
                        <div className="form-group">
                          <label>Tipo</label>
                          <Field name="type" as="select" className="form-select" required>
                            <option>Seleccione</option>
                            <option value="Pensión alimenticia" selected>Pensión alimenticia</option>
                            <option value="Cambio de nombre">Cambio de nombre</option>
                          </Field>
                        </div>
                        <div className="form-group">
                          <label>Contenido</label>
                          <Field component="textarea" type="textarea" name="content" className="form-control"/>
                          <ErrorMessage name="content" component="div"/>
                        </div>
                        <div className="form-group">
                          <h5>Correos de destino</h5>
                        </div>
                        <div className="form-check">
                          <Field type="checkbox" className="form-check-input" name="emails" value="lucas.ign1801@gmail.com" />
                          <label className="form-check-label" htmlFor="flexCheckDefault">
                            lucas.ign1801@gmail.com
                          </label>
                        </div>
                        <div className="form-check">
                          <Field type="checkbox" className="form-check-input" name="emails" value="m.ibarrav@hotmail.com" />
                          <label className="form-check-label" htmlFor="flexCheckDefault">
                            m.ibarrav@hotmail.com
                          </label>
                        </div>
                        <div className="form-check">
                          <Field type="checkbox" className="form-check-input" name="emails" value="camachoj248@gmail.com" />
                          <label className="form-check-label" htmlFor="flexCheckDefault">
                            camachoj248@gmail.com
                          </label>
                        </div>
                        <div className="form-check">
                          <Field type="checkbox" className="form-check-input" name="emails" value="cesarberrios007@gmail.com" />
                          <label className="form-check-label" htmlFor="flexCheckDefault">
                            cesarberrios007@gmail.com
                          </label>
                        </div>
                        <div className="form-group mt-3">
                          <button type="submit" disabled={isSubmitting} className="btn btn-primary">
                            Enviar mensaje
                          </button>
                        </div>
                      </Form>
                  )}
                </Formik>
              </div>
            </div>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
          >
            Made by Lucas and Daniel
          </a>
        </footer>
      </div>
  )
}
